#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "$POSTGRES_DB" <<-EOSQL
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    CREATE USER $KEYCLOAK_DB_USER WITH PASSWORD '$KEYCLOAK_DB_PASSWORD';
    CREATE DATABASE $KEYCLOAK_DB OWNER $KEYCLOAK_DB_USER;
EOSQL

#CREATE USER $MAIN_SERVICE_DB_USER WITH PASSWORD '$MAIN_SERVICE_DB_PASSWORD';
#CREATE DATABASE $MAIN_SERVICE_DB OWNER $MAIN_SERVICE_DB_USER;
#\c $MAIN_SERVICE_DB;
#CREATE EXTENSION IF NOT EXISTS "uuid-ossp";