version: '3.8'

services:
  lcthack-postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: lcthack_user
      POSTGRES_PASSWORD: lcthack_password
      POSTGRES_DB: lcthack
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw

  lcthack-app:
    build:
      context: .
      dockerfile: ./lct_app/Dockerfile
    restart: unless-stopped
    depends_on:
      - lcthack-postgres
    env_file:
      - ./config/postgres.env
    ports:
      - "8081:8081"
    volumes:
      - ./lct_app/:/opt/app-root/src/lct_app:rw
      - ./common/:/opt/app-root/src/common:rw
