version: '3.8'

services:
  lcthack-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: lcthack_user
      POSTGRES_PASSWORD: lcthack_password
      POSTGRES_DB: lcthack
    restart: unless-stopped
    ports:
      - "5400:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw

  lcthack-app:
    build:
      context: .
      dockerfile: ./src/lct_app/Dockerfile
    restart: unless-stopped
    depends_on:
      - lcthack-postgres
    env_file:
      - ./config/postgres.env
      - ./config/giga_chat_api.env
    ports:
      - "8001:8001"
    volumes:
      - ./src/lct_app/:/opt/app-root/src/lct_app:rw
      - ./src/common/:/opt/app-root/src/common:rw
